# Generated by Django 3.1.2 on 2020-10-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201024_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book']},
        ),
    ]
